# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Example format: plugins=(rails git ruby)
# Add wisely, as too many plugins slow down shell startup.
plugins=(ansible git kubectl tempo tmux xtmux)

source $ZSH/oh-my-zsh.sh

# Load configuration files.
for config_file ($HOME/.config/zsh/conf.d/*.zsh); do
  source $config_file
done
