---
- import_tasks: communication.yml
  tags:
    - comm-packages
    - base-packages

- import_tasks: core.yml
  tags:
    - core-packages
    - base-packages

- import_tasks: devops.yml
  tags:
    - devops-packages
    - base-packages

- import_tasks: network.yml
  tags:
    - network-packages
    - base-packages
