---
- name: Install neovim via homebrew
  community.general.homebrew:
    name: "{{ item }}"
  with_items:
    - neovim

- name: Check if plugin manager exists
  stat:
    path: "{{ nvim_config_dir }}/autoload/plug.vim"
  register: vim_plug_result

- name: Install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_config_dir }}/autoload"
  when: not vim_plug_result.stat.exists
